version: "3.7"

services:
  database:
    image: postgres
    container_name: database_goblo
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=omodei
      - POSTGRES_DB=globo
    volumes:
      - pgdata:/data/postgres
    network_mode: host
 
  # app:
  #   build: .
  #   container_name: globo_api
  #   # ports:
  #   #   - 3334:3334
  #   volumes:
  #     - .:/usr/src/app
  #   network_mode: host

volumes:
  pgdata:
    driver: local
